server:
  port: 8080

spring:
  application:
    name: board
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}